// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioProject.DataAccess;

namespace PortfolioProject.DataAccess.Migrations
{
    [DbContext(typeof(PortfolioProjectDbContext))]
    [Migration("20220116170122_AddCvContentTable")]
    partial class AddCvContentTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PortfolioProject.DataAccess.Models.CVContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("CVContent");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "School list",
                            Heading = "Schools",
                            SectionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "College list",
                            Heading = "College",
                            SectionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "University list",
                            Heading = "University",
                            SectionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Next experience",
                            Heading = "Next",
                            SectionId = 2
                        },
                        new
                        {
                            Id = 5,
                            Content = "Gould Tech experience",
                            Heading = "Gould Tech Experience",
                            SectionId = 2
                        });
                });

            modelBuilder.Entity("PortfolioProject.DataAccess.Models.PortfolioEntries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PortfolioEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Portfolio Description",
                            Heading = "Portfolio Heading"
                        });
                });

            modelBuilder.Entity("PortfolioProject.DataAccess.Models.Sections", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Section");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Experiance"
                        });
                });

            modelBuilder.Entity("PortfolioProject.DataAccess.Models.CVContent", b =>
                {
                    b.HasOne("PortfolioProject.DataAccess.Models.Sections", "Section")
                        .WithMany("CVContentList")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("PortfolioProject.DataAccess.Models.Sections", b =>
                {
                    b.Navigation("CVContentList");
                });
#pragma warning restore 612, 618
        }
    }
}
